### ISSUE TITLE
Restrict third-party access to the organization

### ISSUE THREAD

**Issue by brettcannon** [python-modernize/python-modernize#124]
https://github.com/organizations/python-modernize/settings/oauth_application_policy

Basically I'm going to be using GitHub for work and I don't want to authorize my work to access to the project, but that requires setting up application access restrictions which I didn't want to do without @takluyver and @daira saying they are okay with that (unfortunately GitHub doesn't simply let me uncheck access while granting my work's project access to my account).

**Comment by takluyver** [comment]
Security stuff always confuses me - what would this protect from what?

**Comment by daira** [comment]
I've had similar problems with using the same github account for work and other projects; it's irritating. I'm okay with you setting up the access restrictions.

@takluyver It would protect the python-modernize project from being exposed to any vulnerability due to compromise of @brettcannon's access via his work or any third-party apps they use.

**Comment by daira** [comment]
I enabled the restrictions, but it says that a side effect is that "Restricting access ... will disable SSH keys created before February 2014." So please check that you're still able to push (to a test branch, say).

**Comment by takluyver** [comment]
OK, that sounds fine by me. I may have to regenerate some keys, but I can do that as and when I need to.

**Comment by brettcannon** [comment]
Thanks for making the switch, @daira ! And if it turns off an SSH key I will either add it again or simply generate a new one (probably time to anyway).
