### ISSUE TITLE
python-modernize breaks dict.itervalues().next()

### ISSUE THREAD

**Issue by fabioz** [python-modernize/python-modernize#169]
python-modernize breaks `dict.itervalues().next()`.

It changes the code to `six.itervalues(dict)` instead of `next(six.itervalues(dict))`.

**Comment by takluyver** [comment]
I don't think any of us are actively working on python-modernize at the moment, but if you can figure out a way to fix it without breaking other things, I'm happy to look at a PR.

**Comment by fabioz** [comment]
@takluyver thanks for getting back on this... unfortunately, I don't have time to check it either. 

Anyways, thanks for a nice tool to help in porting to python 3.

**Comment by takluyver** [comment]
Fair enough. The issue can of course stay around as information: someone may have time to work on it in the future.

You're welcome, but it's not just my work. Or even mostly. Armin Ronacher wrote it originally, then myself and @daira took over maintenance, and @brettcannon joined us a bit later. Unfortunately, I think we all lose interest after a while, because by design it's a tool that you'll use a lot for a while, and then you don't need it any more.
